version: '2.4'
services:
  blockchain-finder:
    build:
      context: ./app
    container_name: blockchain-finder_finder
    volumes:
      - ./app/src:/app
      - ./blockchain:/blockchain
    ports:
      - 8081:8080
      - 9191:9191
    depends_on:
      - redis
    cpus: '0.5'
    mem_limit: 3G

  redis:
    image: redis
    container_name: blockchain-finder_reids
    cpus: '0.2'
    mem_limit: 700M

  tsung:
    image: prima/tsung
    entrypoint: /start.sh
    container_name: blockchain-finder_tsung
    volumes:
      - ./tsung/tsung_template.xml:/root/.tsung/tsung_template.xml
      - ./tsung/results.txt:/results.txt
      - ./tsung/test_transactions.data:/root/.tsung/test_transactions.data
      - ./tsung/logs:/root/.tsung/log
      - ./tsung/start.sh:/start.sh
    ports:
      - 8091:8091
    depends_on:
      - blockchain-finder
    restart: on-failure
    cpus: '1'
    mem_limit: 256M
